version: '2'
services:
    app:
        build: .
        ports:
            - 8080:5000
        links:
            - mongodb
        environment:
            MONGO_HOST: mongodb
            MONGO_PORT: 27017
    mongodb:
        image: mongo:3.0.2
        ports:
            - 27017:27017